server:
  port: 8070
spring:
  profiles:
    active: dev
    include: secret
  datasource:
    #url: jdbc:postgresql://ksyksy-surl-project-db.internal:5432/surl_dev
    #username: postgres
    #password: UXtRJYEdJqV07c3
    #driver-class-name: org.postgresql.Driver
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    com.koreait.short_url_project_02: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: "My Site"
